### ISSUE TITLE
Installing required packages

### ISSUE THREAD

**Issue by WcaleNieMisker** [Om-Thorat/Term-Spotify#1]
While running 'pip install -r requirements.txt':

Could not install packages due to an OSError: [WinError 2] The specified file could not be found 'C:\\Python311\\Scripts\\markdown-it.exe' -> 'C:\\Python311\\Scripts\\markdown-it.exe.deleteme'

While running app.py:

Traceback (most recent call last):
  File "c:\Users\user\Term-Spotify\app.py", line 2, in <module>
    from textual.reactive import reactive
ModuleNotFoundError: No module named 'textual'

**Comment by Om-Thorat** [comment]
That doesn't seem to be a repositery issue but something with the python config, Can you try running the command as an administrator?
