### ISSUE TITLE
404 not found/nothing happening

### ISSUE THREAD

**Issue by benomat** [Om-Thorat/Term-Spotify#3]
this appears on localhost:443 when running
![image](https://github.com/Om-Thorat/Term-Spotify/assets/71938735/7983247e-e049-4d69-8215-4768b1185d26)

and the console is empty like this
![image](https://github.com/Om-Thorat/Term-Spotify/assets/71938735/6e42aae2-096d-47d0-8ba1-15d39d4a07a2)

**Comment by Om-Thorat** [comment]
Localhost exposes a websocket not a webservice so that is the normal behaviour. for the blank screen are you sure you have spotify open with a song playing?
